from django.urls import path

from . import manage_views
from .views import AdminPanelView, CarHootLoginView, CarHootLogoutView, DashboardView

app_name = "accounts"

urlpatterns = [
    path(
        "admin-panel/courses/<int:course_id>/quizzes/<int:quiz_id>/edit/",
        manage_views.course_quiz_edit,
        name="course_quiz_edit",
    ),
    path(
        "admin-panel/courses/<int:course_id>/quizzes/<int:quiz_id>/delete/",
        manage_views.course_quiz_delete,
        name="course_quiz_delete",
    ),
    path(
        "admin-panel/courses/<int:course_id>/videos/<int:video_id>/edit/",
        manage_views.NestedTrainingVideoUpdateView.as_view(),
        name="course_video_edit",
    ),
    path(
        "admin-panel/courses/<int:course_id>/videos/<int:video_id>/delete/",
        manage_views.course_training_video_delete,
        name="course_video_delete",
    ),
    path(
        "admin-panel/courses/<int:course_id>/section-suggestions/suggest-draft/",
        manage_views.video_sections_suggest_draft_api,
        name="course_sections_suggest_draft",
    ),
    path(
        "admin-panel/courses/<int:course_id>/videos/<int:video_id>/sections/apply/",
        manage_views.video_sections_apply_api,
        name="course_video_sections_apply",
    ),
    path("login/", CarHootLoginView.as_view(), name="login"),
    path("logout/", CarHootLogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("admin-panel/", AdminPanelView.as_view(), name="admin_panel"),
    path(
        "admin-panel/videos/youtube-autofill/",
        manage_views.video_youtube_autofill_api,
        name="video_youtube_autofill",
    ),
    path(
        "admin-panel/videos/ai-description/",
        manage_views.video_ai_description_api,
        name="video_ai_description",
    ),
    path(
        "admin-panel/videos/ai-title/",
        manage_views.video_ai_title_api,
        name="video_ai_title",
    ),
    path(
        "admin-panel/manage/course/<int:course_id>/ai-course-description/",
        manage_views.course_ai_description_generate,
        name="course_ai_description",
    ),
    path(
        "admin-panel/manage/course/<int:course_id>/resources/attach/",
        manage_views.course_resource_attach,
        name="course_resource_attach",
    ),
    path(
        "admin-panel/manage/course/<int:course_id>/resources/<int:resource_id>/detach/",
        manage_views.course_resource_detach,
        name="course_resource_detach",
    ),
    path(
        "admin-panel/manage/course/add/",
        manage_views.CourseCreateView.as_view(),
        name="manage_course_add",
    ),
    path(
        "admin-panel/manage/course/<int:course_pk>/videos/add/",
        manage_views.NestedTrainingVideoCreateView.as_view(),
        name="manage_course_video_add",
    ),
    path(
        "admin-panel/manage/course/<int:course_pk>/videos/sections/suggest-draft/",
        manage_views.video_sections_suggest_draft_api,
        name="manage_course_sections_suggest_draft",
    ),
    path(
        "admin-panel/manage/course/<int:course_pk>/sections/add/",
        manage_views.NestedVideoSectionCreateView.as_view(),
        name="manage_course_section_add",
    ),
    path(
        "admin-panel/manage/course/<int:course_id>/quizzes/add/",
        manage_views.course_quiz_create,
        name="manage_course_quiz_add",
    ),
    path(
        "admin-panel/manage/course/<int:course_id>/quizzes/ai-suggestions/",
        manage_views.course_quiz_ai_suggestions,
        name="course_quiz_ai_suggestions",
    ),
    path(
        "admin-panel/manage/course/<int:course_pk>/questions/add/",
        manage_views.NestedQuestionCreateView.as_view(),
        name="manage_course_question_add",
    ),
    path(
        "admin-panel/manage/course/<int:course_pk>/choices/add/",
        manage_views.NestedAnswerChoiceCreateView.as_view(),
        name="manage_course_choice_add",
    ),
    path(
        "admin-panel/manage/course/<int:course_pk>/ar-tasks/add/",
        manage_views.NestedARTaskCreateView.as_view(),
        name="manage_course_ar_add",
    ),
    path(
        "admin-panel/manage/course/<int:course_pk>/ar-steps/add/",
        manage_views.NestedARTaskStepCreateView.as_view(),
        name="manage_course_ar_step_add",
    ),
    path(
        "admin-panel/manage/course/<int:pk>/",
        manage_views.CourseHubView.as_view(),
        name="manage_course",
    ),
    path(
        "admin-panel/manage/video/add/",
        manage_views.TrainingVideoCreateView.as_view(),
        name="manage_video_add",
    ),
    path(
        "admin-panel/manage/section/add/",
        manage_views.VideoSectionCreateView.as_view(),
        name="manage_section_add",
    ),
    path(
        "admin-panel/manage/quiz/add/",
        manage_views.QuizCreateView.as_view(),
        name="manage_quiz_add",
    ),
    path(
        "admin-panel/manage/question/add/",
        manage_views.QuestionCreateView.as_view(),
        name="manage_question_add",
    ),
    path(
        "admin-panel/manage/choice/add/",
        manage_views.AnswerChoiceCreateView.as_view(),
        name="manage_choice_add",
    ),
    path(
        "admin-panel/manage/ar-task/add/",
        manage_views.ARTaskCreateView.as_view(),
        name="manage_ar_task_add",
    ),
    path(
        "admin-panel/manage/ar-step/add/",
        manage_views.ARTaskStepCreateView.as_view(),
        name="manage_ar_step_add",
    ),
]
