# Generated by Django 5.2.14 on 2026-05-09 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_training_video_field_tweaks'),
        ('resources', '0004_resource_cover_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReadingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Transcript text used as the similarity query.')),
                ('top_k', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_contexts', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_contexts_created', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_contexts', to='courses.trainingvideo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReadingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content_html', models.TextField(blank=True)),
                ('editor_json', models.JSONField(blank=True, default=dict)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('diagrams', models.JSONField(blank=True, default=list)),
                ('generated_by_model', models.CharField(blank=True, max_length=128)),
                ('generated_from', models.JSONField(blank=True, default=dict)),
                ('is_teacher_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_pages', to='study_content.coursereadingcontext')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_page', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReadingSourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_id', models.CharField(max_length=256)),
                ('chunk_text', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('chunk_index', models.IntegerField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('resource_title', models.CharField(blank=True, max_length=255)),
                ('citation_label', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_chunks', to='study_content.coursereadingcontext')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_source_chunks', to='courses.course')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_source_chunks', to='resources.resource')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_source_chunks', to='courses.trainingvideo')),
            ],
            options={
                'ordering': ['context_id', 'pk'],
            },
        ),
    ]
