# Generated by Django 5.2.14 on 2026-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_repair_trainingvideo_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingvideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='transcript_source',
            field=models.CharField(blank=True, default='', help_text='e.g. youtube_captions_manual_en when filled from YouTube captions.', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='youtube_description',
            field=models.TextField(blank=True, default='', help_text='Optional: YouTube video description for AI context (oEmbed does not provide full text).'),
        ),
    ]
