# Generated by Django 5.2.14 on 2026-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_refs',
            field=models.JSONField(blank=True, default=list, help_text='Citation ids from reading context (e.g. B1, V1) for AI-assisted questions.'),
        ),
    ]
